version: "3.9"

services:
  api:
    # 使用JackyW84的镜像
    image: ghcr.io/jackyw84/dify-core:latest
    restart: always
    environment:
      - EDITION=SELF_HOSTED
      - CONSOLE_URL=https://difytest.kimazz.com
      - CONSOLE_API_URL=https://difytest.kimazz.com
      - APP_API_URL=https://difytest.kimazz.com
      - STORAGE_TYPE=local
      - STORAGE_LOCAL_PATH=/app/storage
      - DB_URL=postgresql://postgres:Difytest159753@db:5432/dify
      - REDIS_URL=redis://redis:6379/0
      - OAUTH_REDIRECT_PATH=/console/api/oauth/callback
    depends_on:
      - db
      - redis
    volumes:
      - dify_storage:/app/storage
    labels:
      - traefik.enable=true
      - "traefik.http.routers.dify-api.rule=Host(`difytest.kimazz.com`) && PathPrefix(`/api/`, `/console/api/`)"
      - traefik.http.routers.dify-api.entryPoints=http

  web:
    # 使用JackyW84的镜像
    image: ghcr.io/jackyw84/dify-web:latest
    restart: always
    environment:
      - EDITION=SELF_HOSTED
      - CONSOLE_API_URL=http://api:5001
    depends_on:
      - api
    labels:
      - traefik.enable=true
      - "traefik.http.routers.dify-web.rule=Host(`difytest.kimazz.com`)"
      - traefik.http.routers.dify-web.entryPoints=http

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Difytest159753
      - POSTGRES_DB=dify
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  dify_storage:
  postgres_data:
  redis_data:

networks:
  default:
    name: coolify
    external: true
